/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogobicho.views;

import domain.JogoBicho;
import filters.OnlyIntegerFilter;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import models.JogosApostadosTableModel;
import repositories.JogoBichoDatabaseRepository;
import services.PDFGenerator;

/**
 *
 * @author Daniel
 */
public class TelaDeJogos extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeJogos
     */
    public TelaDeJogos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaJogos = new javax.swing.JTable();
        textNumeroApostado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textValorApostado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnIncluirValor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        TabelaJogos.setModel(JogosTableModel);
        TabelaJogos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TabelaJogos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaJogosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaJogos);

        textNumeroApostado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textNumeroApostado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeroApostadoActionPerformed(evt);
            }
        });
        ((AbstractDocument)textNumeroApostado.getDocument()).setDocumentFilter(
            new OnlyIntegerFilter());

        jLabel1.setText("Número");

        textValorApostado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValorApostado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorApostadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor");

        btnIncluirValor.setText("Incluir");
        btnIncluirValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirValorActionPerformed(evt);
            }
        });
        btnIncluirValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnIncluirValorKeyReleased(evt);
            }
        });

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnClearAll.setText("Apagar conteúdo da tabela");
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textNumeroApostado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textValorApostado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluirValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClearAll)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNumeroApostado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textValorApostado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnIncluirValor)
                                .addComponent(jButton1))))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearAll)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNumeroApostadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroApostadoActionPerformed
        if (!textNumeroApostado.getText().isEmpty()) {
            textValorApostado.requestFocus();
        }
    }//GEN-LAST:event_textNumeroApostadoActionPerformed

    private void textValorApostadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorApostadoActionPerformed
        if (!textValorApostado.getText().isEmpty()) {
            try {
                Float.parseFloat(textValorApostado.getText().replace(",", "."));
                btnIncluirValor.requestFocus();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_textValorApostadoActionPerformed

    private void btnIncluirValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirValorActionPerformed
        addJogo();
        textNumeroApostado.requestFocus();
    }//GEN-LAST:event_btnIncluirValorActionPerformed

    private void btnIncluirValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIncluirValorKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addJogo();
            textNumeroApostado.requestFocus();
        }
    }//GEN-LAST:event_btnIncluirValorKeyReleased

    private void TabelaJogosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaJogosKeyReleased
        int selectedColumn = TabelaJogos.getSelectedColumn();
        if (KeyEvent.VK_DELETE == evt.getKeyCode() && selectedColumn == 0) {
            JogoBicho jogo = JogosTableModel.get(TabelaJogos.getSelectedRow());
            if (jogo != null) {
                int selectedOption = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o número " + jogo.getNumeroApostado());
                
                if (JOptionPane.OK_OPTION == selectedOption) {
                    JogosTableModel.remove(jogo);
                }
            }
        }
    }//GEN-LAST:event_TabelaJogosKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PDFGenerator pdf = new PDFGenerator();
        pdf.generate(JogosTableModel.getList(), new PDFJogos());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        
        int option = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover todos os números da tabela? esta operação não poderá ser revertida.");
        
        if (option == JOptionPane.OK_OPTION) {
            JogosTableModel.clearAll();
        }
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void addJogo() {
        try {
            String numeroApostado = textNumeroApostado.getText();
            String valorApostadoText = textValorApostado.getText().replace(",", ".");
            float valorApostado = Float.parseFloat(valorApostadoText);
            if(JogosTableModel.add(new JogoBicho(numeroApostado, valorApostado))) {
                textNumeroApostado.setText("");
                textValorApostado.setText("");
            }
        } catch (Exception e) {
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaJogos;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnIncluirValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textNumeroApostado;
    private javax.swing.JTextField textValorApostado;
    // End of variables declaration//GEN-END:variables
    private final JogosApostadosTableModel JogosTableModel = new JogosApostadosTableModel(new JogoBichoDatabaseRepository());
}
